sonar.projectKey=shopsphere
sonar.projectName=ShopSphere
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8

sonar.sources=authservice/src/main/java,orderservice/src/main/java,catlogservice/src/main/java,adminservice/src/main/java,paymentservice/src/main/java,GatewayServer/src/main/java,configserver/src/main/java,eurekaserver/src/main/java
sonar.tests=authservice/src/test/java,orderservice/src/test/java,catlogservice/src/test/java,adminservice/src/test/java,paymentservice/src/test/java,GatewayServer/src/test/java,configserver/src/test/java,eurekaserver/src/test/java
sonar.java.binaries=authservice/target/classes,orderservice/target/classes,catlogservice/target/classes,adminservice/target/classes,paymentservice/target/classes,GatewayServer/target/classes,configserver/target/classes,eurekaserver/target/classes

sonar.exclusions=**/target/**,**/Q.java,**/Q2.java
